### PR TITLE
Fixing gallery modal size and background scrolling

### LINKED ISSUE #1167: Gallery Modal Design Fixes (size and background scrolling)
From Colby: 
- Gallery popup should set "overflow: hidden" on body so that you can't scroll the page while inside the popup. This is standard behavior for other popups (e.g. Bootstrap modals https://getbootstrap.com/docs/4.0/components/modal/#live-demo).

### PR DESCRIPTION
**Pull request by sjmiller7**
Fixes #1167

### CODE REVIEW

File: gallery.js [hunk 1]
```diff
@@ -62,25 +62,27 @@ function viewAlbum(albumName) {
...
+    event.stopPropagation();
 });
 
 // Closing modal with background
-$('#modal-background').on('click', function() {
-    $('#modal').hide();
-    $('#modal-background').hide();
+$('#modal-container').on('click', function(event) {
+    $('#modal-container').hide();
+    $('html').css('overflow', 'visible');
```
Comment (colbygallup) [inline gallery.js:85]: Try changing `"visible"` to `""` so that jQuery just deletes the inline CSS

**Review by colbygallup — APPROVED** [review]
tiny fix

**Review by colbygallup — APPROVED** [review]

**Review by peterkos — APPROVED** [review]
LGTM :shipit:
